import {useEffect,useState,FormEvent} from 'react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {users,payments,useAuth,useTask} from './platform';
function Feedback({error,notice}:{error:string;notice:string}){return <>{error&&<p role="alert" className="lab-error">{error}</p>}{notice&&<p role="status" className="lab-notice">{notice}</p>}</>}
export function AccountForm({mode}:{mode:'login'|'register'|'forgot'|'reset'|'invite'|'verify'}){const {refresh}=useAuth(),task=useTask(),navigate=useNavigate(),[search]=useSearchParams();const[type,setType]=useState('PRIVATE'),[fields,setFields]=useState<Record<string,string>>({}),[link,setLink]=useState('');const title={login:'Bentornato.',register:'Il tuo spazio inizia qui.',forgot:'Recupera l’accesso.',reset:'Una nuova password.',invite:'Entra nella tua impresa.',verify:'Verifica la tua email.'}[mode];
 async function submit(e:FormEvent){e.preventDefault();await task.run(async()=>{if(mode==='login'){await users.post('/auth/login',fields);await refresh();navigate('/app');}else if(mode==='register'){const r=await users.post('/auth/register',{...fields,type});task.setNotice(r.data.message);setLink(r.data.verificationUrl??'');}else if(mode==='forgot'){const r=await users.post('/auth/forgot-password',fields);task.setNotice(r.data.message);setLink(r.data.resetUrl??'');}else{const endpoint=mode==='reset'?'reset-password':mode==='invite'?'accept-invite':'verify-email';const r=await users.post('/auth/'+endpoint,{...fields,token:search.get('token')});task.setNotice(r.data.message);}});}
 function input(name:string,label:string,kind='text',auto?:string){return <label className="lab-field" key={name}><span>{label}</span><input name={name} type={kind} required value={fields[name]??''} onChange={e=>setFields({...fields,[name]:e.target.value})} autoComplete={auto} minLength={kind==='password'?10:undefined} maxLength={kind==='password'?72:name==='vatNumber'?11:254}/></label>}
 return <main className="lab-auth"><Link className="lab-logo" to="/">bolletta<span>LAB</span><i/></Link><div className="lab-auth-card"><p className="lab-eyebrow">BOLLETTALAB / IL TUO ACCOUNT</p><h1>{title}</h1><p>{mode==='login'?'Una sola pagina di accesso. Il tuo spazio viene riconosciuto dalle credenziali.':mode==='register'?'Scegli come lavorare. Dopo la registrazione potrai accedere e attivare il piano.':'Segui i passaggi per continuare in sicurezza.'}</p><form onSubmit={submit}>{mode==='register'&&<fieldset className="lab-type"><legend>Tipo di account</legend><label><input type="radio" name="type" checked={type==='PRIVATE'} onChange={()=>setType('PRIVATE')}/>Persona privata</label><label><input type="radio" name="type" checked={type==='COMPANY'} onChange={()=>setType('COMPANY')}/>Impresa</label></fieldset>}{mode==='register'&&input('name',type==='COMPANY'?'Nome e cognome del titolare':'Nome e cognome','text','name')}{['login','register','forgot'].includes(mode)&&input('email','Email','email','email')}{mode==='register'&&type==='COMPANY'&&<div className="lab-form-grid">{input('companyName','Ragione sociale','text','organization')}{input('vatNumber','Partita IVA','text')}{input('address','Indirizzo dell’impresa','text','street-address')}</div>}{['login','register','reset','invite'].includes(mode)&&input('password','Password','password',mode==='login'?'current-password':'new-password')}<Feedback error={task.error} notice={task.notice}/>{link&&<p className="lab-notice">Ambiente di prova: <a href={link}>Apri il link di {mode==='forgot'?'recupero':'verifica'}</a></p>}<button className="lab-btn lab-wide" disabled={task.busy}>{task.busy?'Attendi…':mode==='login'?'Accedi':mode==='register'?'Crea account':mode==='forgot'?'Invia link di recupero':mode==='verify'?'Verifica email':'Conferma'}</button></form>{mode==='login'?<div className="lab-form-links"><Link to="/registrati">Crea un account</Link><Link to="/recupera-password">Password dimenticata?</Link></div>:<p><Link to="/accedi">Vai all’accesso</Link></p>}</div></main>}
export function Billing(){const{user,wallet,refresh,refreshWallet}=useAuth(),task=useTask();const[catalog,setCatalog]=useState<{development:boolean;products:{id:string;name:string;description:string;price:string}[]}|null>(null);useEffect(()=>{void task.run(async()=>setCatalog((await payments.get('/catalog')).data));},[]);
 async function buy(product:string){await task.run(async()=>{await payments.post('/checkout',{product,requestKey:crypto.randomUUID()});await refresh();await refreshWallet();task.setNotice('Operazione di prova completata. Nessun addebito reale.');});}
 return <section className="lab-page"><p className="lab-eyebrow">IL TUO PIANO</p><h1>{wallet?.active?'Più spazio per il tuo lavoro.':'Attiva il tuo spazio.'}</h1><p>Il piano base comprende 80 simulazioni per ogni mese pagato{user?.role==='OWNER'?' e due account agente aggiuntivi al titolare':''}.</p>{catalog?.development&&<p className="lab-notice">Ambiente di sviluppo: i pulsanti confermano pagamenti simulati, senza addebiti. Stripe verrà configurato insieme nella fase finale.</p>}{catalog&&!catalog.development&&<p className="lab-notice">I pagamenti reali saranno disponibili dopo la configurazione di Stripe.</p>}<Feedback error={task.error} notice={task.notice}/><div className="lab-grid3">{catalog?.products.filter(p=>(p.id!=='AGENT_1'||user?.role==='OWNER')&&(wallet?.active?p.id!=='BASE':p.id==='BASE')).map(p=><article className="lab-card" key={p.id}><h2>{p.name}</h2><p>{p.description}</p><p className="lab-price">Prezzo {p.price.toLowerCase()}</p><button className="lab-btn" disabled={task.busy||user?.role==='AGENT'||!catalog.development} onClick={()=>buy(p.id)}>Conferma acquisto di prova</button></article>)}</div>{user?.role==='AGENT'&&<p>Chiedi al titolare di acquistare simulazioni o rinnovare il piano.</p>}</section>}
